FROM %arch%/python:%debianversion%

LABEL maintainer="esteban@gominet.net"
LABEL version="%localversion%"

######################
# SECURITY FIXES
######################
#  - https://security-tracker.debian.org/tracker/CVE-2019-20079
# vim-tiny, sin problema seguridad de bullseye
#   Dependencia de libselinux1 >3.1. que obliga libc6 >= 2.30.
# Se queda fuera, como editor: nano 
#
#  - CVE-2019-3843, CVE-2019-3843 
#  https://security-tracker.debian.org/tracker/CVE-2019-3843
#  Utilizo la versión buster-backports de libsystemd y libudev1
#   En Backport sigue estando el problema (247.2-5~bpo10+1) no se soluciona hasta 247.3-1
#   Pendiente de actualización de backport
#  La afectación es si tiene control del servicio y de un helper exterior. Realmente impacto menor.
#  IGNONAR EN TRIVY
#
#  - CVE-2018-12886  Afecta A ARM en AMD64 no afecta. De momento sólo builds amd64
#   https://security-tracker.debian.org/tracker/CVE-2018-12886
#  IGNORAR EN TRIVY
#
#  - CVE-2019-15847. Afecta sólo a POWER9 binaries.
#   https://security-tracker.debian.org/tracker/CVE-2019-15847
#  IGNORAR EN TRIVY.
#
#  - CVE-2020-1751. Afecta sólo a POWERPC
#  https://security-tracker.debian.org/tracker/CVE-2020-1751
#  IGNORAR EN TRIVY
#
#  - CVE-2020-1752. Solucionado en 2.30 versión en buster 2.28-10
#  https://security-tracker.debian.org/tracker/CVE-2020-1752
#  No hay backport. En Debian etiquetado como minor-issue
#  IGNORAR EN TRIVY
#
#  - CVE-2021-3326. Solucionado en 2.32. Afecta a iconv en lenguage ISO-2022-JP-3
#  https://security-tracker.debian.org/tracker/CVE-2021-3326
#  No hay backport. En Debian etiquetado como minor-issue
#  IGNORAR EN TRIVY
#
#  - CVE-2020-24659. A revisar. Solucionado en 3.6.16, 3.7
#  https://security-tracker.debian.org/tracker/CVE-2020-24659
#  No hay backport. En Debian etiquetado como minor-issue
#  IGNORAR EN TRIVY
#
#  - CVE-2019-12290. A revisar. Solucionado en 2.20
#  https://security-tracker.debian.org/tracker/CVE-2019-12290
#  No hay backport. En Debian etiquetado como minor-issue
#  IGNORAR EN TRIVY

# En entornos windows, se atasca un poco con proxy, virtualizacion de red, etc.. , hay que 
# dejarle aire para establecer las conexiones.
#
ARG PIP_DEFAULT_TIMEOUT=100
ENV PIP_DEFAULT_TIMEOUT=${PIP_DEFAULT_TIMEOUT}

# En desarrollo, para reducir las operaciones.
RUN apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \ 
        zip
        python3 \
        python3-pip \
        ; \
    apt clean; \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install virtualenv \
    tox \
    pylama \
    bandit \
    && mkdir -p /pythondev/output /pythondev/tests /mnt/git
WORKDIR /mnt/git

#ADD docker/rsyncdev.sh /pythondev/rsyncdev.sh
