FROM %arch%/debian:%debianversion%

LABEL maintainer="esteban@gominet.net"
LABEL version="%localversion%"

######################
# SECURITY FIXES
######################
#  - https://security-tracker.debian.org/tracker/CVE-2019-20079
# vim-tiny, sin problema seguridad de bullseye
#   Dependencia de libselinux1 >3.1. que obliga libc6 >= 2.30.
# Se queda fuera, como editor: nano.   Nota: Es por referencia, en bullseye se mantiene también el nano 
#
#  20210906. versión 0.1.2
#
# - CVE-2021-33574. libc-bin,libc6 2.28.10. Solucionado en unstable, hay fix en upstream, pero aun no realizado backport en buster ni bullseye
#  https://sourceware.org/bugzilla/show_bug.cgi?id=27896
#  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989147
#  https://security-tracker.debian.org/tracker/CVE-2021-33574
#  En Debian bullseye etiquetado como minor-issue
#  IGNORAR EN TRIVY
#
#  20210911. versión 0.1.3
#
# - CVE-2021-40528. libgcrypt20 . Solucionado en bookworm, pero aun no realizado backport en buster ni bullseye
#  https://security-tracker.debian.org/tracker/CVE-2021-40528
#  En Debian bullseye etiquetado como minor-issue
#  IGNORAR EN TRIVY
#
  
# runtime dependencies
RUN apt-get update; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        jq \
        less \
        nano \
        rsync \
        unzip \
        xz-utils \
    ; \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y; \
    apt clean

# No se elimina /var/lib/apt/lits a propósito. Cualquier creación a partir de esta imagen base realizará un update.
# Con esto serán rdiff y no descarga completa de listado.
    
